# Generated by Django 5.0.6 on 2024-06-08 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='carsale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Models', models.CharField(max_length=25, null=True)),
            ],
            options={
                'db_table': 'carsale',
            },
        ),
    ]
