# Generated by Django 5.0.6 on 2024-06-08 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carsale',
            name='Models',
        ),
    ]
