# Generated by Django 5.0.6 on 2024-06-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_remove_carsale_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='carsale',
            name='Model',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
