# Generated by Django 5.0.6 on 2024-06-10 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_rename_brand_carsale_brand_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='image',
            table='cars_image',
        ),
    ]
