# Generated by Django 5.0.6 on 2024-06-10 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_delete_image_remove_carsale_brand_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='carsale',
            table='carsale',
        ),
    ]
