# Generated by Django 5.0.6 on 2024-06-10 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_carsale_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carsale',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='carsale',
            name='model',
        ),
    ]
