# Generated by Django 5.0.6 on 2024-06-10 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_image_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='image',
            table=None,
        ),
    ]
