# Generated by Django 5.0.6 on 2024-06-09 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_carsale_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carsale',
            name='Brand',
        ),
    ]
