# Generated by Django 5.0.6 on 2024-06-09 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_remove_carsale_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='carsale',
            name='Brand',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
